name: "Update BaiduNetdisk"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Update For BaiduNetdisk
        id: update-app
        run: ./scripts/check-update-baidunetdisk.sh
        shell: bash

      - name: Set up Docker Buildx
        if: ${{ steps.update-app.outputs.version != '' }}
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: ${{ steps.update-app.outputs.version != '' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push BaiduNetdisk Image
        if: ${{ steps.update-app.outputs.version != '' }}
        id: docker-build
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:baidunetdisk"
          push: true
          tags: ${{ format('{0}:{1}-auto', 'stormyyd/baidunetdisk', steps.update-app.outputs.version) }}

      - name: Render template
        if: ${{ steps.update-app.outputs.version != '' }}
        id: template
        uses: chuhlomin/render-template@v1.6
        with:
          template: .github/auto-update-pull-request-template.md
          vars: |
            appname: BaiduNetdisk
            version: ${{ steps.update-app.outputs.version }}
            imagename: "stormyyd/baidunetdisk"

      - name: Create Pull Request
        if: ${{ steps.update-app.outputs.version != '' }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: ${{ format('Upgrade baidunetdisk to version {0}', steps.update-app.outputs.version) }}
          title: ${{ format('[BOT] Upgrade BaiduNetdisk to version {0}', steps.update-app.outputs.version) }}
          body: ${{ steps.template.outputs.result }}
          delete-branch: true
          branch: auto-update/baidunetdisk
          assignees: stormyyd
          reviewers: stormyyd
          labels: automated
